var fr = {
    "page_title": "L.O.G Music Service Client WebApp",
    "title": "Bienvenue sur le formulaire du service client L.O.G Music Entertainment",
    "form_info": "Tous les champs sont obligatoires",
    "category_label": "Votre demande concerne quelle catégorie : ",
    "choose_label": "Choisir",
    "distribution_label": "Distribution",
    "object_label": "Objet de la demande : ",
    "referent_label": "Attribution référent L.O.G",
    "spotify_ads_label": "Campagne Spotify Ads",
    "cover_label": "Conception cover",
    "vevo_label": "Création chaine VEVO",
    "tiktok_account_label": "Création compte TikTok",
    "lyrics_label": "Gestion des lyrics",
    "redistribution_label": "Redistribution (Changement de nom d'artiste / cover)",
    "audio_label": "Traitement audio son",
    "copyright_label": "Vérification copyright (en cas de non validation)",
    "communication_label": "Communication",
    "certification_label": "Certification comptes plateformes / réseaux (Spotify, Apple, Boomplay, Deezer)",
    "chart_conception_label": "Conception charte graphique pour artiste/label",
    "pressbook_label": "Conception pressbook",
    "site_label": "Conception site internet artiste/label",
    "strategy_label": "Consulting strategie de communication",
    "fanlink_pre_label": "Création fanlink pre-release",
    "fanlink_label": "Création fanlink release",
    "express_label": "Distribution express",
    "hightlight_label": "Mise en avant  Boomplay / Stillac",
    "media_tour_label": "Organisation média tour / réseaux sociaux",
    "publish_label": "Publication sur nos pages",
    "video_label": "Vidéo",
    "tiktok_ads_label": "Campagne TikTok Ads",
    "youtube_ads_label": "Campagne YouTube Ads",
    "official_youtube_label": "Création compte YouTube officiel",
    "distribution_vevo_label": "Distribution VEVO",
    "contract_label": "Contrat",
    "account_label": "Gestion de compte",
    "other_label": "Autres",
    "nickname_label": "Nom d'artiste : ",
    "email_label": "E-mail : ",
    "phone_label": "Numéro de téléhpone : ",
    "description_label": "Description : "
};
